#use_frameworks!
inhibit_all_warnings!

platform :ios, '8.0'
source 'https://github.com/xudusheng/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'BXAppEngine_Example' do
  pod 'BXToolKit'
  pod 'BXUIKit'
  pod 'BXAppEngine', :path => '../'

  target 'BXAppEngine_Tests' do
    inherit! :search_paths

  end
end
